import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/store/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es"> {/**Indicar que va a ser en español */}
      <body className={inter.className}>
        <Providers> {/**Provider de redux, lo colocamos aca porque dentro de app es donde necestio que mis paginas puedan usar cualquier estado global */}
          { children }
        </Providers>

      </body>
    </html>
  )
}
